version: '3.3'
volumes:
  postgres-data:
services:
  db:
    image: postgres:12.3
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - DB_NAME=hatched_development
    ports:
      - 5433:5432
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    stdin_open: true
    tty: true
    environment:
      - WEB_CONCURRENCY=1
      - RAILS_MAX_THREADS=1
    env_file:
      - .env
    volumes:
      - .:/hatched
    ports:
      - 3000:3000
    depends_on:
      - db
